[tool.poetry]
name = "vertyces"
version = "0.1.0"
description = ""
authors = ["Julien GASPAR LOPES <julien.gaspar-lopes@napta.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
